import 'dart:io';

import 'package:native_toolchain_zig/native_toolchain_zig.dart';

/// Generates an asset adapter from native_toolchain_zig binding metadata.
Future<void> generateBackend({
  required Directory project,
  required List<GeneratedDartFunction> functions,
  String outputPath = 'lib/src/generated/runtime_bindings.g.dart',
}) async {
  if (functions.isEmpty) {
    throw const FormatException('Zig bindings contain no exported functions');
  }

  final out = StringBuffer()
    ..writeln('// GENERATED by dart_zig generate. DO NOT EDIT.')
    ..writeln('// ignore_for_file: type=lint')
    ..writeln("import 'dart:ffi' as ffi;")
    ..writeln("import '../ffi.g.dart' as native;")
    ..writeln("import 'package:dart_zig/src/runtime_abi.g.dart' as abi;")
    ..writeln("import 'package:dart_zig/src/runtime_bindings.dart';")
    ..writeln("import 'package:dart_zig/dart_zig.dart' as dz;");
  out
    ..writeln('')
    ..writeln(
      '/// Forwards the shared runtime ABI to this generated native asset.',
    )
    ..writeln('class _AssetBindings implements RuntimeBindings {')
    ..writeln('  /// Creates a stateless adapter for this native asset.')
    ..writeln('  const _AssetBindings();')
    ..writeln(
      '  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(native.dz_buffer_release));',
    )
    ..writeln('  @override')
    ..writeln('  ffi.NativeFinalizer get bufferFinalizer => _finalizer;');
  for (final method in functions) {
    final forwarded = method.parameters
        .map((parameter) {
          final name = parameter.name;
          return parameter.type.isPointer ? '$name.cast()' : name;
        })
        .join(', ');
    var call = 'native.${method.name}($forwarded)';
    if (method.returnType.isPointer) call += '.cast()';
    final result = method.returnType.render(namedTypePrefix: 'abi.');
    final parameters = method.parameters
        .map(
          (parameter) =>
              '${parameter.type.render(namedTypePrefix: 'abi.')} ${parameter.name}',
        )
        .join(', ');
    out.writeln('  @override $result ${method.name}($parameters) => $call;');
  }
  out.writeln('}');
  out
    ..writeln('')
    ..writeln('/// Opens a session using this package\'s native asset.')
    ..writeln('dz.NativeSession createSession({')
    ..writeln('  dz.DiagnosticSink? onDiagnostic,')
    ..writeln('  dz.SessionTransport? transport,')
    ..writeln('  Future<void> Function()? stopExternal,')
    ..writeln('  int maxPending = 256,')
    ..writeln('  int maxBytes = 8 * 1024 * 1024,')
    ..writeln('  int? maxPendingBytes,')
    ..writeln('  int queueCapacity = 256,')
    ..writeln('  int workers = 1,')
    ..writeln('  int batchSize = 32,')
    ..writeln('}) => dz.NativeSession(')
    ..writeln('  bindings: const _AssetBindings(),')
    ..writeln('  onDiagnostic: onDiagnostic,')
    ..writeln('  transport: transport,')
    ..writeln('  stopExternal: stopExternal,')
    ..writeln('  maxPending: maxPending,')
    ..writeln('  maxBytes: maxBytes,')
    ..writeln('  maxPendingBytes: maxPendingBytes,')
    ..writeln('  queueCapacity: queueCapacity,')
    ..writeln('  workers: workers,')
    ..writeln('  batchSize: batchSize,')
    ..writeln(');')
    ..writeln('')
    ..writeln('/// Opens a native request bridge using this package\'s asset.')
    ..writeln('dz.NativeBridge createBridge({')
    ..writeln('  int maxMessages = 64,')
    ..writeln('  int maxBytes = 1024 * 1024,')
    ..writeln('  int maxRequests = 64,')
    ..writeln('  Future<void> Function()? stopNative,')
    ..writeln('}) => dz.NativeBridge(')
    ..writeln('  bindings: const _AssetBindings(),')
    ..writeln('  maxMessages: maxMessages,')
    ..writeln('  maxBytes: maxBytes,')
    ..writeln('  maxRequests: maxRequests,')
    ..writeln('  stopNative: stopNative,')
    ..writeln(');');

  final file = File('${project.path}/$outputPath');
  await file.parent.create(recursive: true);
  await file.writeAsString(out.toString());

  final hasWebBuild = Directory('${project.path}/web').existsSync();
  if (hasWebBuild) {
    final web = StringBuffer()
      ..writeln('// GENERATED by dart_zig generate. DO NOT EDIT.')
      ..writeln("import 'package:dart_zig/dart_zig.dart' as dz;")
      ..writeln()
      ..writeln('/// Opens a session backed by the initialized Wasm module.')
      ..writeln('dz.NativeSession createSession({')
      ..writeln('  dz.DiagnosticSink? onDiagnostic,')
      ..writeln('  dz.SessionTransport? transport,')
      ..writeln('  Future<void> Function()? stopExternal,')
      ..writeln('  int maxPending = 256,')
      ..writeln('  int maxBytes = 8 * 1024 * 1024,')
      ..writeln('  int? maxPendingBytes,')
      ..writeln('  int queueCapacity = 256,')
      ..writeln('  int workers = 1,')
      ..writeln('  int batchSize = 32,')
      ..writeln('}) => dz.NativeSession(')
      ..writeln('  onDiagnostic: onDiagnostic,')
      ..writeln('  transport: transport,')
      ..writeln('  stopExternal: stopExternal,')
      ..writeln('  maxPending: maxPending,')
      ..writeln('  maxBytes: maxBytes,')
      ..writeln('  maxPendingBytes: maxPendingBytes,')
      ..writeln('  queueCapacity: queueCapacity,')
      ..writeln('  workers: workers,')
      ..writeln('  batchSize: batchSize,')
      ..writeln(');');
    final webFile = File(
      '${project.path}/lib/src/generated/web_bindings.g.dart',
    );
    await webFile.writeAsString(web.toString());
  }

  final sessionFile = File('${project.path}/lib/src/generated/session.g.dart');
  final webSelection = hasWebBuild
      ? " if (dart.library.js_interop) 'web_bindings.g.dart'"
      : '';
  await sessionFile.writeAsString(
    '// GENERATED by dart_zig generate. DO NOT EDIT.\n'
    "export 'runtime_bindings.g.dart'"
    '$webSelection'
    ' show createSession;\n',
  );
}
