import 'dart:convert';
import 'dart:io';

/// Generates typed endpoints from Zig handlers or explicit route declarations.
Future<void> generateProtocol({
  required Directory project,
  required Directory sharedZigDir,
}) async {
  final handlers = File('${project.path}/zig/src/handlers.zig');
  final protocol = File('${project.path}/zig/src/protocol.zig');
  if (handlers.existsSync() && protocol.existsSync()) {
    throw const FormatException(
      'Use either handlers.zig or protocol.zig, not both',
    );
  }
  if (!handlers.existsSync() && !protocol.existsSync()) return;
  final typedHandlers = handlers.existsSync();
  final moduleName = typedHandlers ? 'handlers' : 'protocol';
  final sourceFile = typedHandlers ? handlers : protocol;
  final outputPath = typedHandlers
      ? 'lib/src/generated/api.g.dart'
      : 'lib/src/generated/protocol.g.dart';

  final version = await Process.run('zig', ['version']);
  if (version.exitCode != 0) {
    throw ProcessException(
      'zig',
      ['version'],
      '${version.stderr}',
      version.exitCode,
    );
  }
  final minor = int.parse('${version.stdout}'.trim().split('.')[1]);
  if (minor != 15 && minor != 16) {
    throw StateError('Protocol generation supports Zig 0.15 and 0.16');
  }
  final dump =
      '${sharedZigDir.path}/src/${typedHandlers ? 'handler' : 'protocol'}_dump_0$minor.zig';
  final arguments = [
    'run',
    '--dep',
    moduleName,
    '--dep',
    'dart_zig',
    '-Mroot=$dump',
    '--dep',
    'dart_zig',
    '-M$moduleName=${sourceFile.absolute.path}',
    '-Mdart_zig=${sharedZigDir.path}/src/root.zig',
  ];
  final result = await Process.run(
    'zig',
    arguments,
    workingDirectory: project.path,
  );
  if (result.exitCode != 0) {
    throw ProcessException(
      'zig',
      arguments,
      '${result.stderr}',
      result.exitCode,
    );
  }
  final metadata = jsonDecode('${result.stdout}') as Map<String, Object?>;
  final routes = (metadata['routes'] as List<Object?>)
      .cast<Map<String, Object?>>();
  if (routes.isEmpty) throw const FormatException('Protocol has no routes');
  final ids = <int>{};
  for (final route in routes) {
    final id = route['id'];
    if (id is! int || id < 1 || id > 0xffffffff || !ids.add(id)) {
      throw FormatException('Invalid or duplicate protocol route ID: $id');
    }
  }
  final source = _render(routes, typedHandlers: typedHandlers);
  final output = File('${project.path}/$outputPath');
  await output.parent.create(recursive: true);
  await output.writeAsString(source);
  final formatted = await Process.run('dart', ['format', output.path]);
  if (formatted.exitCode != 0) {
    throw ProcessException(
      'dart',
      ['format', output.path],
      '${formatted.stderr}',
      formatted.exitCode,
    );
  }
  stdout.writeln('Wrote ${output.path}');
}

String _render(
  List<Map<String, Object?>> routes, {
  required bool typedHandlers,
}) {
  final apiName = typedHandlers ? 'ZigApi' : 'ProtocolApi';
  final out = StringBuffer()
    ..writeln('// GENERATED by dart_zig generate. DO NOT EDIT.')
    ..writeln("import 'dart:typed_data';")
    ..writeln("import 'package:dart_zig/dart_zig.dart';")
    ..writeln()
    ..writeln(
      '/// Typed ${typedHandlers ? 'handlers' : 'routes'} declared in zig/src/${typedHandlers ? 'handlers' : 'protocol'}.zig.',
    )
    ..writeln('final class $apiName {')
    ..writeln('  /// Binds all routes to one native session.')
    ..writeln('  $apiName(NativeSession session)');
  for (var i = 0; i < routes.length; i++) {
    final route = routes[i];
    final name = _identifier(route['name']);
    final title = _title(name);
    final kind = route['kind'];
    if (kind != 'call' &&
        kind != 'stream' &&
        kind != 'signal' &&
        kind != 'state') {
      throw FormatException('Unsupported route kind: $kind');
    }
    final initializer = switch (kind) {
      'call' || 'stream' => () {
        final input = _type(route['request'] as Map<String, Object?>);
        final output = _type(route['response'] as Map<String, Object?>);
        final endpoint = kind == 'call' ? 'callEndpoint' : 'streamEndpoint';
        return '_$name = session.$endpoint<$input, $output>(route: ${route['id']}, input: const ${title}RequestCodec(), output: const ${title}ResponseCodec())';
      }(),
      _ =>
        '$name = SignalEndpoint(session, ${route['id']}, const _${title}Codec(), state: ${kind == 'state'})',
    };
    out.writeln(
      "    ${i == 0 ? ':' : ','} $initializer${i == routes.length - 1 ? ';' : ''}",
    );
  }
  out.writeln();
  for (final route in routes) {
    final name = _identifier(route['name']);
    final kind = route['kind'];
    if (kind == 'signal' || kind == 'state') {
      out.writeln(
        '  /// ${kind == 'state' ? 'Replaying state' : 'Signal'} endpoint for the Zig $name route.',
      );
      out.writeln(
        '  final SignalEndpoint<${_type(route['message'] as Map<String, Object?>)}> $name;',
      );
      continue;
    }
    final input = _type(route['request'] as Map<String, Object?>);
    final output = _type(route['response'] as Map<String, Object?>);
    final publicOutput =
        route['response'] is Map<String, Object?> &&
            _isEmpty(route['response'] as Map<String, Object?>)
        ? 'void'
        : output;
    final call = route['kind'] == 'call';
    out.writeln('  /// Stable route ID for the Zig $name handler.');
    out.writeln('  static const int ${name}Route = ${route['id']};');
    out.writeln(
      '  final ${call ? 'CallEndpoint' : 'StreamEndpoint'}<$input, $output> _$name;',
    );
    out.writeln('  /// Invokes the Zig $name route.');
    out.writeln(
      '  ${call ? 'Future' : 'Stream'}<$publicOutput> $name($input request, {Duration? timeout}) => _$name.${call ? 'call' : 'open'}(request, timeout: timeout);',
    );
    if (call) {
      out.writeln('  /// Starts a cancellable $name call.');
      out.writeln(
        '  TypedCall<$publicOutput> start${_title(name)}($input request, {Duration? timeout}) => _$name.start(request, timeout: timeout);',
      );
    }
  }
  out.writeln('}');

  for (final route in routes) {
    final name = _identifier(route['name']);
    final title = _title(name);
    if (route['kind'] == 'signal' || route['kind'] == 'state') {
      final message = route['message'] as Map<String, Object?>;
      out
        ..writeln(
          'final class _${title}Codec implements BinaryCodec<${_type(message)}> {',
        )
        ..writeln('  const _${title}Codec();')
        ..writeln('  @override Uint8List encode(${_type(message)} value) {')
        ..writeln('    final writer = BinaryWriter();');
      _write(out, message, 'value', '    ');
      out
        ..writeln('    return writer.finish();')
        ..writeln('  }')
        ..writeln('  @override ${_type(message)} decode(Uint8List bytes) {')
        ..writeln('    final reader = BinaryReader(bytes);')
        ..writeln('    final value = ${_read(message)};')
        ..writeln('    reader.finish();')
        ..writeln('    return value;')
        ..writeln('  }')
        ..writeln('}');
      continue;
    }
    final request = route['request'] as Map<String, Object?>;
    final response = route['response'] as Map<String, Object?>;
    out
      ..writeln(
        'final class ${title}RequestCodec implements BinaryCodec<${_type(request)}> {',
      )
      ..writeln('  /// Encodes and decodes the Zig $name request.')
      ..writeln('  const ${title}RequestCodec();')
      ..writeln('  @override Uint8List encode(${_type(request)} value) {')
      ..writeln('    final writer = BinaryWriter();');
    _write(out, request, 'value', '    ');
    out
      ..writeln('    return writer.finish();')
      ..writeln('  }')
      ..writeln('  @override ${_type(request)} decode(Uint8List bytes) {')
      ..writeln('    final reader = BinaryReader(bytes);')
      ..writeln('    final value = ${_read(request)};')
      ..writeln('    reader.finish();')
      ..writeln('    return value;')
      ..writeln('  }')
      ..writeln('}')
      ..writeln(
        'final class ${title}ResponseCodec implements BinaryCodec<${_type(response)}> {',
      )
      ..writeln('  /// Encodes and decodes the Zig $name response.')
      ..writeln('  const ${title}ResponseCodec();')
      ..writeln('  @override Uint8List encode(${_type(response)} value) {')
      ..writeln('    final writer = BinaryWriter();');
    _write(out, response, 'value', '    ');
    out
      ..writeln('    return writer.finish();')
      ..writeln('  }')
      ..writeln('  @override ${_type(response)} decode(Uint8List bytes) {')
      ..writeln('    final reader = BinaryReader(bytes);')
      ..writeln('    final value = ${_read(response)};')
      ..writeln('    reader.finish();')
      ..writeln('    return value;')
      ..writeln('  }')
      ..writeln('}');
  }
  return out.toString();
}

String _identifier(Object? value) {
  final name = '$value';
  if (!RegExp(r'^[a-zA-Z][a-zA-Z0-9_]*$').hasMatch(name)) {
    throw FormatException('Invalid Zig protocol identifier: $name');
  }
  return name;
}

String _title(String name) => name[0].toUpperCase() + name.substring(1);

bool _isEmpty(Map<String, Object?> metadata) =>
    metadata['kind'] == 'empty' ||
    (metadata['kind'] == 'struct' &&
        (metadata['fields'] as List<Object?>).isEmpty);

String _type(Map<String, Object?> metadata) => switch (metadata['kind']) {
  'int' when const [8, 16, 32, 64].contains(metadata['bits']) => 'int',
  'float' when const [32, 64].contains(metadata['bits']) => 'double',
  'bool' => 'bool',
  'text' => 'String',
  'bytes' => 'Uint8List',
  'empty' => 'Null',
  'struct' when (metadata['fields'] as List<Object?>).isEmpty => 'Null',
  'struct' =>
    '({${(metadata['fields'] as List<Object?>).map((field) {
      final item = field as Map<String, Object?>;
      return '${_type(item['type'] as Map<String, Object?>)} ${_identifier(item['name'])}';
    }).join(', ')}})',
  final Object? kind => throw FormatException(
    'Unsupported protocol type: $kind',
  ),
};

String _method(Map<String, Object?> metadata) => switch (metadata['kind']) {
  'int' when const [8, 16, 32, 64].contains(metadata['bits']) =>
    '${metadata['signed'] == true ? 'i' : 'u'}${metadata['bits']}',
  'float' when const [32, 64].contains(metadata['bits']) =>
    'f${metadata['bits']}',
  'bool' => 'boolean',
  'text' => 'string',
  'bytes' => 'bytes',
  final Object? kind => throw FormatException('Unsupported scalar type: $kind'),
};

void _write(
  StringBuffer out,
  Map<String, Object?> metadata,
  String value,
  String indent,
) {
  if (metadata['kind'] == 'struct') {
    for (final field in metadata['fields'] as List<Object?>) {
      final item = field as Map<String, Object?>;
      _write(
        out,
        item['type'] as Map<String, Object?>,
        '$value.${_identifier(item['name'])}',
        indent,
      );
    }
    return;
  }
  if (metadata['kind'] == 'empty') return;
  out.writeln('$indent writer.${_method(metadata)}($value);');
}

String _read(Map<String, Object?> metadata) {
  if (_isEmpty(metadata)) return 'null';
  if (metadata['kind'] == 'bytes') return 'Uint8List.fromList(reader.bytes())';
  if (metadata['kind'] == 'struct') {
    final fields = (metadata['fields'] as List<Object?>).map((field) {
      final item = field as Map<String, Object?>;
      return '${_identifier(item['name'])}: ${_read(item['type'] as Map<String, Object?>)}';
    });
    return '(${fields.join(', ')})';
  }
  return 'reader.${_method(metadata)}()';
}
