import 'dart:io';

/// Writes the app's stable import for its runtime and generated API.
Future<void> generatePublicEntrypoint({
  required Directory project,
  required String packageName,
}) async {
  final output = File('${project.path}/lib/src/generated/generated.dart');
  const marker = '// GENERATED by dart_zig generate. DO NOT EDIT.';
  if (output.existsSync() && !output.readAsStringSync().startsWith(marker)) {
    throw StateError(
      'Refusing to overwrite ${output.path}: it is not generated by dart_zig',
    );
  }

  final hasWeb = Directory('${project.path}/web').existsSync();
  final source = StringBuffer()
    ..writeln(marker)
    ..writeln('/// Dart and Zig API generated for this package.')
    ..writeln('library;')
    ..writeln();

  if (hasWeb) {
    source
      ..writeln("import 'dart:typed_data';")
      ..writeln("import 'package:dart_zig/dart_zig.dart' as dz;")
      ..writeln()
      ..writeln("export 'package:dart_zig/dart_zig.dart' hide initializeZig;");
  } else {
    source.writeln("export 'package:dart_zig/dart_zig.dart';");
  }
  source.writeln("export 'session.g.dart' show createSession;");

  if (!hasWeb) {
    source.writeln("export 'runtime_bindings.g.dart' show createBridge;");
  }

  if (File('${project.path}/zig/src/handlers.zig').existsSync()) {
    source.writeln("export 'api.g.dart';");
  } else if (File('${project.path}/zig/src/protocol.zig').existsSync()) {
    source.writeln("export 'protocol.g.dart';");
  }

  if (hasWeb) {
    source
      ..writeln()
      ..writeln('/// Initializes this package\'s WebAssembly module on Web.')
      ..writeln('///')
      ..writeln(
        '/// This is a no-op on the Dart VM. Supply [wasmUri] or [wasmBytes]',
      )
      ..writeln('/// to load a module from another location.')
      ..writeln(
        'Future<void> initializeZig({Uri? wasmUri, Uint8List? wasmBytes}) =>',
      )
      ..writeln('    dz.initializeZig(')
      ..writeln("      wasmUri: wasmUri ?? Uri.parse('$packageName.wasm'),")
      ..writeln('      wasmBytes: wasmBytes,')
      ..writeln('    );');
  }

  await output.writeAsString(source.toString());
  stdout.writeln('Wrote ${output.path}');
}
