// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:native_toolchain_zig`.
@ffi.DefaultAsset('package:web_example/web_example.dart')
library;

import 'dart:ffi' as ffi;

final class RuntimeFrame extends ffi.Struct {
  @ffi.Uint64()
  external int id;

  @ffi.Uint32()
  external int route;

  @ffi.Uint32()
  external int kind;

  @ffi.Uint32()
  external int code;

  @ffi.UintPtr()
  external int length;

  external ffi.Pointer<ffi.Uint8> data;

  external ffi.Pointer<ffi.Void> owner;

}

final class RuntimeStats extends ffi.Struct {
  @ffi.Uint64()
  external int submitted;

  @ffi.Uint64()
  external int delivered;

  @ffi.Uint64()
  external int wakes;

  @ffi.Uint64()
  external int copied_bytes;

  @ffi.Uint64()
  external int log_drops;

  @ffi.UintPtr()
  external int input_messages;

  @ffi.UintPtr()
  external int output_messages;

  @ffi.UintPtr()
  external int input_bytes;

  @ffi.UintPtr()
  external int output_bytes;

}

@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Void>)>(symbol: 'dz_initialize')
external bool dz_initialize(ffi.Pointer<ffi.Void> data);

@ffi.Native<ffi.Pointer<dz_Bridge> Function(ffi.Int64, ffi.UintPtr, ffi.UintPtr, ffi.UintPtr)>(symbol: 'dz_create')
external ffi.Pointer<dz_Bridge> dz_create(int port, int count, int bytes, int pending);

@ffi.Native<ffi.Void Function(ffi.Pointer<dz_Bridge>)>(symbol: 'dz_close')
external void dz_close(ffi.Pointer<dz_Bridge> bridge);

@ffi.Native<ffi.Void Function(ffi.Pointer<dz_Bridge>)>(symbol: 'dz_destroy')
external void dz_destroy(ffi.Pointer<dz_Bridge> bridge);

@ffi.Native<ffi.Void Function(ffi.Pointer<dz_Bridge>)>(symbol: 'dz_acknowledge')
external void dz_acknowledge(ffi.Pointer<dz_Bridge> bridge);

@ffi.Native<ffi.Bool Function(ffi.Pointer<dz_Bridge>, ffi.Uint64)>(symbol: 'dz_is_pending')
external bool dz_is_pending(ffi.Pointer<dz_Bridge> bridge, int id);

@ffi.Native<ffi.Uint8 Function(ffi.Pointer<dz_Bridge>, ffi.Pointer<ffi.Pointer<dz_Packet>>)>(symbol: 'dz_take_request')
external int dz_take_request(ffi.Pointer<dz_Bridge> bridge, ffi.Pointer<ffi.Pointer<dz_Packet>> out);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<dz_Packet>)>(symbol: 'dz_packet_id')
external int dz_packet_id(ffi.Pointer<dz_Packet> packet);

@ffi.Native<ffi.UintPtr Function(ffi.Pointer<dz_Packet>)>(symbol: 'dz_packet_length')
external int dz_packet_length(ffi.Pointer<dz_Packet> packet);

@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.Pointer<dz_Packet>)>(symbol: 'dz_packet_bytes')
external ffi.Pointer<ffi.Uint8> dz_packet_bytes(ffi.Pointer<dz_Packet> packet);

@ffi.Native<ffi.Void Function(ffi.Pointer<dz_Packet>)>(symbol: 'dz_packet_free')
external void dz_packet_free(ffi.Pointer<dz_Packet> packet);

@ffi.Native<ffi.Uint8 Function(ffi.Pointer<dz_Bridge>, ffi.Uint64, ffi.Uint8, ffi.Pointer<ffi.Uint8>, ffi.UintPtr)>(symbol: 'dz_reply')
external int dz_reply(ffi.Pointer<dz_Bridge> bridge, int id, int kind, ffi.Pointer<ffi.Uint8> bytes, int len);

@ffi.Native<ffi.Uint32 Function()>(symbol: 'dz_protocol_version')
external int dz_protocol_version();

@ffi.Native<ffi.Pointer<dz_Runtime> Function(ffi.Int64, ffi.UintPtr, ffi.UintPtr, ffi.Uint32, ffi.UintPtr)>(symbol: 'dz_runtime_create')
external ffi.Pointer<dz_Runtime> dz_runtime_create(int port, int count, int bytes, int tasks, int workers);

@ffi.Native<ffi.Void Function(ffi.Pointer<dz_Runtime>)>(symbol: 'dz_runtime_stop')
external void dz_runtime_stop(ffi.Pointer<dz_Runtime> runtime);

@ffi.Native<ffi.Bool Function(ffi.Pointer<dz_Runtime>)>(symbol: 'dz_runtime_stopped')
external bool dz_runtime_stopped(ffi.Pointer<dz_Runtime> runtime);

@ffi.Native<ffi.Void Function(ffi.Pointer<dz_Runtime>)>(symbol: 'dz_runtime_destroy')
external void dz_runtime_destroy(ffi.Pointer<dz_Runtime> runtime);

@ffi.Native<ffi.Void Function(ffi.Pointer<dz_Runtime>)>(symbol: 'dz_runtime_acknowledge')
external void dz_runtime_acknowledge(ffi.Pointer<dz_Runtime> runtime);

@ffi.Native<ffi.Uint8 Function(ffi.Pointer<dz_Runtime>, ffi.Uint32, ffi.Uint32, ffi.Pointer<ffi.Uint8>, ffi.UintPtr, ffi.Uint64, ffi.Pointer<ffi.Uint64>)>(symbol: 'dz_runtime_submit')
external int dz_runtime_submit(ffi.Pointer<dz_Runtime> runtime, int route, int kind, ffi.Pointer<ffi.Uint8> data, int length, int timeout_ns, ffi.Pointer<ffi.Uint64> out_id);

@ffi.Native<ffi.Uint8 Function(ffi.Pointer<dz_Runtime>, ffi.Uint32, ffi.Pointer<ffi.Uint8>, ffi.UintPtr)>(symbol: 'dz_runtime_send_signal')
external int dz_runtime_send_signal(ffi.Pointer<dz_Runtime> runtime, int route, ffi.Pointer<ffi.Uint8> data, int length);

@ffi.Native<ffi.Uint8 Function(ffi.Pointer<dz_Runtime>, ffi.Uint64, ffi.Uint32, ffi.Uint32, ffi.Pointer<ffi.Uint8>, ffi.UintPtr)>(symbol: 'dz_runtime_callback_reply')
external int dz_runtime_callback_reply(ffi.Pointer<dz_Runtime> runtime, int id, int callback_id, int code, ffi.Pointer<ffi.Uint8> data, int length);

@ffi.Native<ffi.Uint8 Function(ffi.Pointer<dz_Runtime>, ffi.Uint64)>(symbol: 'dz_runtime_cancel')
external int dz_runtime_cancel(ffi.Pointer<dz_Runtime> runtime, int id);

@ffi.Native<ffi.UintPtr Function(ffi.Pointer<dz_Runtime>, ffi.Pointer<RuntimeFrame>, ffi.UintPtr)>(symbol: 'dz_runtime_poll')
external int dz_runtime_poll(ffi.Pointer<dz_Runtime> runtime, ffi.Pointer<RuntimeFrame> output, int capacity);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(symbol: 'dz_buffer_retain')
external void dz_buffer_retain(ffi.Pointer<ffi.Void> owner);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(symbol: 'dz_buffer_release')
external void dz_buffer_release(ffi.Pointer<ffi.Void> owner);

@ffi.Native<ffi.Uint8 Function(ffi.Pointer<dz_Runtime>, ffi.Uint64)>(symbol: 'dz_runtime_grant')
external int dz_runtime_grant(ffi.Pointer<dz_Runtime> runtime, int id);

@ffi.Native<ffi.Bool Function(ffi.Pointer<dz_Runtime>)>(symbol: 'dz_runtime_ready_to_destroy')
external bool dz_runtime_ready_to_destroy(ffi.Pointer<dz_Runtime> runtime);

@ffi.Native<ffi.Void Function(ffi.Pointer<dz_Runtime>, ffi.Pointer<RuntimeStats>)>(symbol: 'dz_runtime_stats')
external void dz_runtime_stats(ffi.Pointer<dz_Runtime> runtime, ffi.Pointer<RuntimeStats> output);

@ffi.Native<ffi.UintPtr Function()>(symbol: 'dz_live_buffers')
external int dz_live_buffers();

@ffi.Native<ffi.UintPtr Function()>(symbol: 'dz_live_buffer_bytes')
external int dz_live_buffer_bytes();

@ffi.Native<ffi.UintPtr Function(ffi.Pointer<ffi.Void>)>(symbol: 'dz_buffer_capacity')
external int dz_buffer_capacity(ffi.Pointer<ffi.Void> owner);

final class dz_Bridge extends ffi.Opaque {}

final class dz_Packet extends ffi.Opaque {}

final class dz_Runtime extends ffi.Opaque {}
