// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// ABI types generated by `package:native_toolchain_zig`.
library;

import 'dart:ffi' as ffi;

final class RuntimeFrame extends ffi.Struct {
  @ffi.Uint64()
  external int id;

  @ffi.Uint32()
  external int route;

  @ffi.Uint32()
  external int kind;

  @ffi.Uint32()
  external int code;

  @ffi.UintPtr()
  external int length;

  external ffi.Pointer<ffi.Uint8> data;

  external ffi.Pointer<ffi.Void> owner;
}

final class RuntimeStats extends ffi.Struct {
  @ffi.Uint64()
  external int submitted;

  @ffi.Uint64()
  external int delivered;

  @ffi.Uint64()
  external int wakes;

  @ffi.Uint64()
  external int copied_bytes;

  @ffi.Uint64()
  external int log_drops;

  @ffi.UintPtr()
  external int input_messages;

  @ffi.UintPtr()
  external int output_messages;

  @ffi.UintPtr()
  external int input_bytes;

  @ffi.UintPtr()
  external int output_bytes;
}

final class dz_Bridge extends ffi.Opaque {}

final class dz_Packet extends ffi.Opaque {}

final class dz_Runtime extends ffi.Opaque {}
