import 'dart:ffi';
import 'dart:isolate';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

import 'ffi.g.dart' as native;
import 'generated/runtime_bindings.g.dart';
import 'native_buffer.dart';
import 'runtime_error.dart';
import 'transport.dart';

/// Native FFI adapter; Dart FFI declarations are generated by the toolchain CLI.
final class NativeTransport implements SessionTransport {
  NativeTransport({
    Object? bindings,
    required int queueCapacity,
    required int maxBytes,
    required int maxPending,
    required int workers,
    required int batchSize,
  }) : bindings =
           (bindings as RuntimeBindings?) ?? const GeneratedRuntimeBindings() {
    if (!this.bindings.dz_initialize(NativeApi.initializeApiDLData)) {
      throw const NativeException('protocol', 'Cannot initialize Dart API DL');
    }
    _port = ReceivePort('dart_zig.session');
    try {
      _batch = calloc<native.RuntimeFrame>(batchSize);
      _batchSize = batchSize;
      _id = calloc<Uint64>();
      _scratch = calloc<Uint8>(128);
      _handle = this.bindings.dz_runtime_create(
        _port.sendPort.nativePort,
        queueCapacity,
        maxBytes,
        maxPending,
        workers,
      );
      if (_handle == nullptr) {
        throw const NativeException(
          'allocation',
          'Cannot create native session',
        );
      }
    } catch (_) {
      _port.close();
      calloc.free(_batch);
      calloc.free(_id);
      calloc.free(_scratch);
      rethrow;
    }
    _port.listen((_) {
      if (_destroyed) return;
      this.bindings.dz_runtime_acknowledge(_handle);
      onWake?.call();
    });
  }
  final RuntimeBindings bindings;
  late final ReceivePort _port;
  late final Pointer<native.dz_Runtime> _handle;
  Pointer<native.RuntimeFrame> _batch = nullptr;
  late final int _batchSize;
  Pointer<Uint64> _id = nullptr;
  Pointer<Uint8> _scratch = nullptr;
  int _capacity = 128;
  bool _destroyed = false;
  @override
  void Function()? onWake;
  @override
  int get protocolVersion => bindings.dz_protocol_version();
  @override
  int get schemaFingerprint => bindings.dz_schema_fingerprint();
  Pointer<Uint8> _copy(Uint8List bytes) {
    if (bytes.length > _capacity) {
      final next = calloc<Uint8>(bytes.length);
      calloc.free(_scratch);
      _scratch = next;
      _capacity = bytes.length;
    }
    _scratch.asTypedList(bytes.length).setAll(0, bytes);
    return _scratch;
  }

  @override
  ({int status, int id}) submit(
    int route,
    int kind,
    Uint8List bytes,
    int timeoutNs,
  ) {
    final status = bindings.dz_runtime_submit(
      _handle,
      route,
      kind,
      _copy(bytes),
      bytes.length,
      timeoutNs,
      _id,
    );
    return (status: status, id: status == 0 ? _id.value : 0);
  }

  @override
  int sendSignal(int route, Uint8List bytes) => bindings.dz_runtime_send_signal(
    _handle,
    route,
    _copy(bytes),
    bytes.length,
  );
  @override
  int callbackReply(int id, int callbackId, int code, Uint8List bytes) =>
      bindings.dz_runtime_callback_reply(
        _handle,
        id,
        callbackId,
        code,
        _copy(bytes),
        bytes.length,
      );
  @override
  void cancel(int id) {
    bindings.dz_runtime_cancel(_handle, id);
  }

  @override
  void grant(int id) {
    bindings.dz_runtime_grant(_handle, id);
  }

  @override
  List<TransportFrame> poll(int capacity) {
    final count = bindings.dz_runtime_poll(
      _handle,
      _batch,
      capacity < _batchSize ? capacity : _batchSize,
    );
    final result = <TransportFrame>[];
    var index = 0;
    try {
      for (; index < count; index++) {
        final f = _batch[index];
        final buffer = NativeBuffer.fromOwned(
          f.owner,
          f.data,
          f.length,
          bindings: bindings,
        );
        result.add(TransportFrame(f.id, f.route, f.kind, f.code, buffer));
      }
      return result;
    } catch (_) {
      for (final f in result) {
        f.buffer.dispose();
      }
      for (; index < count; index++) {
        bindings.dz_buffer_release(_batch[index].owner);
      }
      rethrow;
    }
  }

  @override
  TransportStats get stats {
    final pointer = calloc<native.RuntimeStats>();
    try {
      bindings.dz_runtime_stats(_handle, pointer);
      final v = pointer.ref;
      return TransportStats(
        submitted: v.submitted,
        delivered: v.delivered,
        wakes: v.wakes,
        copiedBytes: v.copied_bytes,
        logDrops: v.log_drops,
        inputMessages: v.input_messages,
        outputMessages: v.output_messages,
        inputBytes: v.input_bytes,
        outputBytes: v.output_bytes,
      );
    } finally {
      calloc.free(pointer);
    }
  }

  @override
  bool get stopped => _destroyed || bindings.dz_runtime_stopped(_handle);
  @override
  bool get readyToDestroy =>
      _destroyed || bindings.dz_runtime_ready_to_destroy(_handle);
  @override
  void stop() {
    if (!_destroyed) {
      bindings.dz_runtime_stop(_handle);
    }
  }

  @override
  void destroy() {
    if (_destroyed) return;
    _destroyed = true;
    _port.close();
    onWake = null;
    bindings.dz_runtime_destroy(_handle);
    calloc.free(_batch);
    calloc.free(_id);
    calloc.free(_scratch);
  }
}

SessionTransport createTransport({
  Object? bindings,
  required int queueCapacity,
  required int maxBytes,
  required int maxPending,
  required int workers,
  required int batchSize,
}) => NativeTransport(
  bindings: bindings,
  queueCapacity: queueCapacity,
  maxBytes: maxBytes,
  maxPending: maxPending,
  workers: workers,
  batchSize: batchSize,
);
int get liveBuffers => const GeneratedRuntimeBindings().dz_live_buffers();
int get liveBufferBytes =>
    const GeneratedRuntimeBindings().dz_live_buffer_bytes();

/// Native assets load through Dart build hooks; no explicit startup is required.
Future<void> initializeZig({Uri? wasmUri, Uint8List? wasmBytes}) async {}
