#!/usr/bin/env python3
"""Generate a runtime adapter around CLI-generated FFI (never FFI declarations).

For another native asset use --interface-import to implement this package's
RuntimeBindings interface, and --native-import to select its generated bindings.
"""
import argparse
import pathlib
import re

root = pathlib.Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser()
parser.add_argument('--ffi', default='lib/src/ffi.g.dart')
parser.add_argument('--output', default='lib/src/generated/runtime_bindings.g.dart')
parser.add_argument('--class-name', default='GeneratedRuntimeBindings')
parser.add_argument('--native-import', default='../ffi.g.dart')
parser.add_argument('--interface-import')
parser.add_argument('--abi-import', default='../ffi.g.dart')
args = parser.parse_args()
source = (root / args.ffi).read_text()
classes = re.findall(r'final class (\w+) extends', source)
functions = []
for match in re.finditer(r'^external\s+([^;{}()]+?)\s+(dz_\w+)\((.*?)\);', source, re.S | re.M):
    result, name, parameters = match.groups()
    if name not in ('dz_initialize', 'dz_protocol_version', 'dz_schema_fingerprint', 'dz_sync_sum') and not name.startswith(('dz_runtime_', 'dz_buffer_', 'dz_live_')):
        continue
    functions.append((' '.join(result.split()), name, [p.strip() for p in parameters.split(',') if p.strip()]))
if len(functions) < 15:
    raise SystemExit('Missing runtime declarations in CLI-generated FFI')

def qualify(text):
    for name in classes:
        text = re.sub(r'\b'+name+r'\b', 'abi.'+name, text)
    return text

docs = {
    'dz_sync_sum': 'Runs the bundled short synchronous sum using this same application asset.',
    'dz_runtime_send_signal': 'Copies a one-way signal into the input queue; success means admission only.',
    'dz_initialize': 'Initializes Dart API DL using the VM-provided initialization pointer.',
    'dz_protocol_version': 'Returns the transport ABI version required by this asset.',
    'dz_schema_fingerprint': 'Returns the application schema fingerprint.',
    'dz_runtime_create': 'Creates a runtime; null indicates invalid limits or allocation failure.',
    'dz_runtime_stop': 'Stops admission and wakes workers without joining them.',
    'dz_runtime_stopped': 'Reports whether shutdown has started.',
    'dz_runtime_ready_to_destroy': 'Reports whether every runtime worker has exited.',
    'dz_runtime_destroy': 'Joins workers and frees storage; external native users must already stop.',
    'dz_runtime_acknowledge': 'Acknowledges a Dart wake so a later event can post another notification.',
    'dz_runtime_submit': 'Copies an input frame and writes its request ID on successful admission.',
    'dz_runtime_callback_reply': 'Copies a callback result for a still-live request.',
    'dz_runtime_cancel': 'Invalidates a request and wakes blocked native producers.',
    'dz_runtime_grant': 'Grants a production credit to a live stream.',
    'dz_runtime_poll': 'Transfers up to capacity frames into output; release each returned buffer owner.',
    'dz_runtime_stats': 'Writes a snapshot into caller-owned stats storage.',
    'dz_buffer_retain': 'Acquires another reference to a live buffer from this native asset.',
    'dz_buffer_release': 'Releases one owned reference; the final release recycles or frees storage.',
    'dz_buffer_capacity': 'Returns allocated storage capacity for a live buffer owner.',
    'dz_live_buffers': 'Returns asset-wide live buffer allocations, including pooled storage.',
    'dz_live_buffer_bytes': 'Returns asset-wide allocated buffer capacity in bytes.',
}

out = ['// GENERATED by tool/generate_backend.py from CLI-generated FFI.', '// ignore_for_file: type=lint', "import 'dart:ffi' as ffi;", "import '"+args.native_import+"' as native;", "import '"+args.abi_import+"' as abi;"]
if args.interface_import:
    out.append("import '"+args.interface_import+"';")
else:
    out += ['/// Application-specific entry points for the shared runtime ABI.', '///\n/// Generated adapters implement this interface around CLI-produced FFI.\n/// Pointers and buffer owners must stay within the asset that created them.\n/// Status-returning operations use 0 success, 1 full, 2 closed, 3 invalid,\n/// 4 allocation failure, and 5 oversized payload. Poll returns a frame count.\nabstract interface class RuntimeBindings {', '/// Fallback release callback belonging to this same native asset.\nffi.NativeFinalizer get bufferFinalizer;']
    for result, name, params in functions:
        out.append('/// '+docs[name])
        out.append(qualify(result)+' '+name+'('+', '.join(qualify(p) for p in params)+');')
    out.append('}')
out += ['/// Delegates to the native asset selected by the CLI-generated bindings.', 'class '+args.class_name+' implements RuntimeBindings {', '/// Creates a stateless adapter for this generated native asset.\nconst '+args.class_name+'();', 'static final _bufferFinalizer = ffi.NativeFinalizer(ffi.Native.addressOf(native.dz_buffer_release));', '@override ffi.NativeFinalizer get bufferFinalizer => _bufferFinalizer;']
for result, name, params in functions:
    forwarded = []
    for param in params:
        arg = param.split()[-1]
        if 'ffi.Pointer<' in param: arg += '.cast()'
        forwarded.append(arg)
    call = 'native.'+name+'('+', '.join(forwarded)+')'
    if 'ffi.Pointer<' in result: call += '.cast()'
    out.append('@override '+qualify(result)+' '+name+'('+', '.join(qualify(p) for p in params)+') => '+call+';')
out.append('}')
path = root / args.output
path.parent.mkdir(parents=True, exist_ok=True)
path.write_text('\n'.join(out)+'\n')
print('Generated runtime adapter: '+args.output)
