#!/usr/bin/env python3
"""Generate matching Dart/Zig models and typed Dart APIs from schema.json.

FFI declarations are generated separately by native_toolchain_zig's CLI.
"""
import hashlib
import json
import pathlib
import argparse
import collection_codegen as collections
from schema_validation import validate, PRIMITIVES

root = pathlib.Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser()
parser.add_argument('--root', type=pathlib.Path, default=root)
args = parser.parse_args()
root = args.root.resolve()
schema = json.loads((root / 'schema.json').read_text())
validate(schema)
aliases = schema.get('types', {})
enums, models, unions = (schema[k] for k in ('enums', 'models', 'unions'))
primitives = PRIMITIVES
types = []

def add(t):
    if t in types: return
    if t.endswith('?'): add(t[:-1])
    elif t.endswith('[]'): add(t[:-2])
    elif t in aliases:
        for child in collections.children(aliases[t]): add(child)
    elif t not in primitives and t not in enums and t not in models and t not in unions:
        raise ValueError('Unknown type: ' + t)
    types.append(t)

for t in primitives: add(t)
for t in aliases: add(t)
for op in schema['operations']:
    add(op['input']); add(op['output'])
for fields in [*models.values(), *unions.values()]:
    for t in fields.values(): add(t)
for t in [*enums, *models, *unions]: add(t)
for callback in schema.get('callbacks', {}).values():
    add(callback['input']); add(callback['output'])
# Stable generated order, independent of Python's set hash seed.
types.sort()
names = {t: str(i) for i, t in enumerate(types)}

def dt(t):
    if t.endswith('?'): return dt(t[:-1]) + '?'
    if t.endswith('[]'): return 'List<' + dt(t[:-2]) + '>'
    if t in {'i8','u8','i16','u16','i32'}: return 'int'
    if t in {'i128','u128'}: return 'BigInt'
    if t == 'f32': return 'double'
    return {'i64':'int','u64':'int','u32':'int','f64':'double','bool':'bool','string':'String','bytes':'Uint8List','void':'void'}.get(t,t)
def zt(t):
    if t.endswith('?'): return '?' + zt(t[:-1])
    if t.endswith('[]'): return '[]const ' + zt(t[:-2])
    return {'string':'[]const u8','bytes':'[]const u8','void':'void'}.get(t,t)
def cap(s): return s[:1].upper() + s[1:]
def dr(t): return '_read' + names[t] + '(reader)'
def dw(t,v): return '_write' + names[t] + '(writer, ' + v + ');'
def zr(t): return 'try read' + names[t] + '(reader, allocator)'
def zw(t,v): return 'try write' + names[t] + '(writer, ' + v + ');'

fingerprint = int.from_bytes(hashlib.sha256(json.dumps(schema, separators=(',', ':')).encode()).digest()[:4], 'little')
d = ['// GENERATED by tool/generate_models.py. DO NOT EDIT.', '// ignore_for_file: type=lint, unused_element', "import 'dart:async';", "import 'dart:typed_data';", "import '../codec.dart';", "import '../session.dart';", "import '../signals.dart';", "import '../sync_native.dart' if (dart.library.js_interop) '../sync_web.dart' as sync;", '/// Fingerprint checked against the application native asset at facade creation.', f'const schemaFingerprint = {fingerprint};']
z = ['// GENERATED by tool/generate_models.py. DO NOT EDIT.', 'const std = @import("std");', 'const codec = @import("dart_zig").codec;', f'pub const schema_fingerprint: u32 = {fingerprint};']
for name, spec in aliases.items():
    d.append('/// Schema '+spec['kind']+' representation.\ntypedef '+name+' = '+collections.dart_type(spec,dt)+';')
    z.append('pub const '+name+' = '+collections.zig_type(spec,zt)+';')
for name, fields in enums.items():
    d.append('/// Schema enumeration; declaration order determines wire tags.\n'+'enum '+name+' { '+', '.join(fields)+' }')
    z.append('pub const '+name+' = enum(u32) { '+', '.join(fields)+' };')
for name, fields in models.items():
    d += ['/// Schema message shared with Zig.\n///\n/// Collection and byte fields are retained by reference; this is not a deep copy.\nfinal class '+name+' {', '/// Creates a message from its schema fields.\nconst '+name+'({'+', '.join('required this.'+f for f in fields)+'});']
    d += ['/// The `'+f+'` field encoded as `'+t+'`.\nfinal '+dt(t)+' '+f+';' for f,t in fields.items()]
    d += ['}']
    z += ['pub const '+name+' = struct {'] + [f+': '+zt(t)+',' for f,t in fields.items()] + ['};']
for name, variants in unions.items():
    d.append('/// Tagged schema union; wire tags follow variant declaration order.\nsealed class '+name+' { const '+name+'(); }')
    for field,t in variants.items():
        variant=name+cap(field)
        d.append('/// The `'+field+'` variant of ['+name+'].\nfinal class '+variant+' extends '+name+' { const '+variant+'(this.value); final '+dt(t)+' value; }')
    z.append('pub const '+name+' = union(enum(u32)) { '+', '.join(f+': '+zt(t) for f,t in variants.items())+' };')

for t in types:
    n=names[t]
    d.append('void _write'+n+'(BinaryWriter writer, '+dt(t)+' value) {' if t!='void' else 'void _write'+n+'(BinaryWriter writer) {')
    z.append('fn write'+n+'(writer: *codec.Writer, value: '+zt(t)+') !void {' if t!='void' else 'fn write'+n+'(_: *codec.Writer, _: void) !void {')
    if t.endswith('?'):
        child=t[:-1]
        d.append('writer.boolean(value != null); if (value != null) { '+dw(child,'value')+' }')
        z.append('try writer.boolean(value != null); if (value) |item| { '+zw(child,'item')+' }')
    elif t.endswith('[]'):
        child=t[:-2]
        d.append('if (value.length > 1000000) throw RangeError("Collection too large"); writer.u32(value.length); for (final item in value) { '+dw(child,'item')+' }')
        z.append('if (value.len > 1000000) return error.TooLarge; try writer.int(u32, @intCast(value.len)); for (value) |item| { '+zw(child,'item')+' }')
    elif t in aliases:
        dart, zig = collections.write(aliases[t],dw,zw); d.append(dart); z.append(zig)
    elif t in models:
        d += [dw(typ,'value.'+field) for field,typ in models[t].items()]
        z += [zw(typ,'value.'+field) for field,typ in models[t].items()]
    elif t in enums:
        d.append('writer.u32(value.index);'); z.append('try writer.int(u32, @intFromEnum(value));')
    elif t in unions:
        d.append('switch (value) {'); z.append('switch (value) {')
        for tag,(field,typ) in enumerate(unions[t].items()):
            d.append('case '+t+cap(field)+'(:final value): writer.u32('+str(tag)+'); '+dw(typ,'value'))
            z.append('.'+field+' => |item| { try writer.int(u32, '+str(tag)+'); '+zw(typ,'item')+' },')
        d.append('}'); z.append('}')
    elif t!='void':
        d.append('writer.'+{'bool':'boolean'}.get(t,t)+'(value);')
        z.append('try writer.'+({**{t:'int('+t+', value)' for t in primitives if t[0] in 'iu'},'f32':'float32(value)','f64':'float(value)','bool':'boolean(value)','bytes':'blob(value)','string':'string(value)'}[t])+';')
    d.append('}'); z.append('}')
    d.append(dt(t)+' _read'+n+'(BinaryReader reader) {')
    uses_alloc = t.endswith('?') or t.endswith('[]') or t in models or t in unions or t in aliases
    z.append('fn read'+n+'(reader: *codec.Reader, '+('allocator' if uses_alloc else '_')+': std.mem.Allocator) !'+zt(t)+' {' if t!='void' else 'fn read'+n+'(_: *codec.Reader, _: std.mem.Allocator) !void {')
    if t.endswith('?'):
        d.append('return reader.boolean() ? '+dr(t[:-1])+' : null;')
        z.append('return if (try reader.boolean()) '+zr(t[:-1])+' else null;')
    elif t.endswith('[]'):
        child=t[:-2]
        d.append('return List<'+dt(child)+'>.generate(reader.collectionLength(), (_) => '+dr(child)+');')
        z.append('const count = try reader.int(u32); if (count > 1000000) return error.TooLarge; const values = try allocator.alloc('+zt(child)+', count); for (values) |*item| item.* = '+zr(child)+'; return values;')
    elif t in aliases:
        dart, zig = collections.read(t,aliases[t],dt,zt,dr,zr); d.append(dart); z.append(zig)
    elif t in models:
        d.append('return '+t+'('+', '.join(f+': '+dr(typ) for f,typ in models[t].items())+');')
        z.append('return .{'+', '.join('.'+f+' = '+zr(typ) for f,typ in models[t].items())+'};')
    elif t in enums:
        d.append('final tag = reader.u32(); if (tag >= '+str(len(enums[t]))+') throw const FormatException("Invalid enum tag"); return '+t+'.values[tag];')
        z.append('return switch (try reader.int(u32)) { '+', '.join(str(i)+' => .'+v for i,v in enumerate(enums[t]))+', else => error.InvalidTag };')
    elif t in unions:
        d.append('return switch (reader.u32()) { '+', '.join(str(i)+' => '+t+cap(f)+'('+dr(typ)+')' for i,(f,typ) in enumerate(unions[t].items()))+', _ => throw const FormatException("Invalid union tag") };')
        z.append('return switch (try reader.int(u32)) { '+', '.join(str(i)+' => .{ .'+f+' = '+zr(typ)+' }' for i,(f,typ) in enumerate(unions[t].items()))+', else => error.InvalidTag };')
    elif t!='void':
        d.append('return reader.'+{'bool':'boolean'}.get(t,t)+'();')
        z.append('return '+('try reader.'+{**{t:'int('+t+')' for t in primitives if t[0] in 'iu'},'f32':'float32()','f64':'float()','bool':'boolean()','bytes':'blob()','string':'string()'}[t])+';')
    d.append('}'); z.append('}')

for name in [*models, *unions, *aliases]:
    d.append('/// Checked binary conversion for ['+name+'].\n///\n/// Decoded byte fields borrow the input; copy them for independent mutation.\nfinal class '+name+'Codec implements BinaryCodec<'+name+'> { const '+name+'Codec(); @override Uint8List encode('+name+' value) { final writer = BinaryWriter(); '+dw(name,'value')+' return writer.finish(); } @override '+name+' decode(Uint8List bytes) { final reader = BinaryReader(bytes); final value = '+dr(name)+'; reader.finish(); return value; } }')
for name in [*models, *unions, *aliases]:
    z.append('pub fn encode'+name+'(writer: *codec.Writer, value: '+name+') !void { '+zw(name,'value')+' }')
    z.append('pub fn decode'+name+'(reader: *codec.Reader, allocator: std.mem.Allocator) !'+name+' { return '+zr(name)+'; }')
z.append('pub const Operations = struct {')
d.append('/// Typed facade for the bundled schema, bound to one native session.\n///\n/// Constructing the facade validates the native schema fingerprint.\nfinal class GeneratedApi {\n/// Validates the schema and binds calls to [session].\nGeneratedApi(this.session) { session.checkSchema(schemaFingerprint); }\n/// Session owning the application tasks, callbacks, and native objects.\nfinal NativeSession session;')
for op in schema['operations']:
    name, inp, out = op['name'],op['input'],op['output']
    z.append('pub const '+name+': u32 = '+str(op['id'])+';')
    summaries = {
        'sum': 'Adds two signed integers on a native worker.',
        'publish': 'Publishes a typed message to current signal listeners.',
        'squares': 'Streams successive squares under subscription credit control.',
        'counterCreate': 'Creates a session-owned counter and returns its opaque handle.',
        'counterAdd': 'Atomically updates a counter identified by a live handle.',
        'counterDispose': 'Removes a native counter handle; stale handles fail.',
        'transform': 'Requests a registered Dart callback and resumes on its result.',
        'echo': 'Returns the submitted bytes through the native transport.',
        'roundTripRecord': 'Round-trips a structured record through the native codec.',
        'roundTripValue': 'Round-trips a tagged union through the native codec.',
        'emitLog': 'Attempts to publish a best-effort structured native log.',
    }
    d.append('/// '+summaries.get(name, 'Invokes the `'+name+'` schema operation.')+'\n///\n/// [timeout] covers admission and execution. Native failures propagate as\n/// session errors; malformed result bytes fail decoding.')
    body='final writer = BinaryWriter(); '+dw(inp,'input')
    if op.get('stream'):
        d.append('Stream<'+dt(out)+'> '+name+'('+dt(inp)+' input, {Duration? timeout}) { '+body+' return session.stream('+str(op['id'])+', writer.finish(), timeout: timeout).map((bytes) { final reader = BinaryReader(bytes); final value = '+dr(out)+'; reader.finish(); return value; }); }')
    else:
        body += ' final bytes = await session.call('+str(op['id'])+', writer.finish(), timeout: timeout).result; final reader = BinaryReader(bytes); '
        body += (dr(out)+'; reader.finish();' if out=='void' else 'final value = '+dr(out)+'; reader.finish(); return value;')
        d.append('Future<'+dt(out)+'> '+name+'('+dt(inp)+' input, {Duration? timeout}) async { '+body+' }')
for name, callback in schema.get('callbacks', {}).items():
    inp, out = callback['input'], callback['output']
    d.append('/// Registers a typed callback; unregister its ID through [session] when done.\nint register'+name+'(FutureOr<'+dt(out)+'> Function('+dt(inp)+') callback) => session.registerCallback((bytes) async { final reader = BinaryReader(bytes); final input = '+dr(inp)+'; reader.finish(); final result = await callback(input); final writer = BinaryWriter(maxBytes: session.maxBytes); '+dw(out,'result')+' return writer.finish(); });')
for op in schema['operations']:
    if 'callback' not in op: continue
    spec = op['callback']; callback = schema['callbacks'][spec['type']]
    fields = models[op['input']]
    args = ['required '+dt(t)+' '+f for f,t in fields.items() if f != spec['field']]
    args += ['required FutureOr<'+dt(callback['output'])+'> Function('+dt(callback['input'])+') callback', 'Duration? timeout']
    construct = ', '.join(f+': '+('id' if f == spec['field'] else f) for f in fields)
    d.append('/// Invokes ['+op['name']+'] with a scoped callback registration.\n///\n/// Unregisters on completion or failure. The callback may await native calls.\n///\n/// {@example /bin/toolkit.dart#typed-callback}\nFuture<'+dt(op['output'])+'> '+op['name']+'With({'+', '.join(args)+'}) async { final id = register'+spec['type']+'(callback); try { return await '+op['name']+'('+op['input']+'('+construct+'), timeout: timeout); } finally { session.unregisterCallback(id); } }')
for op in schema.get('sync_operations', []):
    if op['signature'] != 'i64_i64_to_i64':
        raise SystemExit('Unsupported synchronous signature: '+op['signature'])
    d.append('/// Executes the short native operation synchronously on the Dart thread.\n///\n/// Nonzero native status becomes a session error. Avoid blocking work here.\nint '+op['name']+'(int a, int b) => sync.'+op['name']+'(session, a, b);')
for signal in schema['signals']:
    d.append('/// Typed broadcast events; no replay and bounded paused-subscription storage.\n///\n/// Subscribe before invoking an operation that emits an event.\nStream<'+signal['type']+'> get '+signal['name']+' => session.signals.where((event) => event.route == '+str(signal['id'])+').map((event) => const '+signal['type']+'Codec().decode(event.bytes));')
for endpoint in schema.get('endpoints', []):
    d.append('/// Session-scoped bidirectional endpoint; dispose each received pack.\nlate final '+ 'SignalEndpoint<'+endpoint['type']+'> '+endpoint['name']+' = SignalEndpoint(session, '+str(endpoint['id'])+', const '+endpoint['type']+'Codec(), state: '+str(endpoint.get('state',False)).lower()+');')
d.append('}'); z.append('};')
(root/'lib/src/generated').mkdir(parents=True, exist_ok=True)
(root/'zig/src/generated').mkdir(parents=True, exist_ok=True)
(root/'lib/src/generated/models.g.dart').write_text('\n'.join(d)+'\n')
(root/'zig/src/generated/models.zig').write_text('\n'.join(z)+'\n')
print(f'Generated {len(models)} models, {len(unions)} unions, {len(schema["operations"])} operations; schema {fingerprint}')

# Native typed endpoint emitters share the metadata/attachment envelope.
with (root/'zig/src/generated/models.zig').open('a') as f:
    for endpoint in schema.get('endpoints', []):
        name=endpoint['name']; typ=endpoint['type']; route=endpoint['id']
        f.write('pub fn emit'+cap(name)+'(runtime: anytype, allocator: std.mem.Allocator, message: '+typ+', binary: []const u8) !void {\n')
        f.write('var metadata: codec.Writer = .{ .allocator = allocator, .max_bytes = 8 * 1024 * 1024 }; defer metadata.deinit(); try encode'+typ+'(&metadata, message);\n')
        f.write('var envelope: codec.Writer = .{ .allocator = allocator, .max_bytes = 8 * 1024 * 1024 }; defer envelope.deinit(); try envelope.blob(metadata.bytes.items); try envelope.blob(binary); try runtime.trySignal('+str(route)+', envelope.bytes.items); }\n')
