// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:native_toolchain_zig`.
@ffi.DefaultAsset('package:native_requests_example/native_requests_example.dart')
library;

import 'dart:ffi' as ffi;

/// Submits the example request from a native thread.
@ffi.Native<ffi.Uint64 Function(ffi.Pointer<dz_Bridge>)>(symbol: 'dz_demo_submit')
external int dz_demo_submit(ffi.Pointer<dz_Bridge> bridge);

/// Cancels an example request from Zig.
@ffi.Native<ffi.Bool Function(ffi.Pointer<dz_Bridge>, ffi.Uint64)>(symbol: 'dz_demo_cancel')
external bool dz_demo_cancel(ffi.Pointer<dz_Bridge> bridge, int id);

/// Consumes a reply from Dart in the example's native asset.
@ffi.Native<ffi.Bool Function(ffi.Pointer<dz_Bridge>, ffi.Uint64, ffi.Uint8, ffi.Pointer<ffi.Uint8>, ffi.UintPtr)>(symbol: 'dz_demo_consume')
external bool dz_demo_consume(ffi.Pointer<dz_Bridge> bridge, int id, int kind, ffi.Pointer<ffi.Uint8> bytes, int len);

final class dz_Bridge extends ffi.Opaque {}
