// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:native_toolchain_zig`.
@ffi.DefaultAsset('package:runtime_features_example/runtime_features_example.dart')
library;

import 'dart:ffi' as ffi;

/// Synchronous example operation outside the session protocol.
@ffi.Native<ffi.Uint8 Function(ffi.Int64, ffi.Int64, ffi.Pointer<ffi.Int64>)>(symbol: 'dz_sync_sum')
external int dz_sync_sum(int a, int b, ffi.Pointer<ffi.Int64> output);

/// Web-friendly synchronous example operation.
@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>(symbol: 'dz_web_sum')
external double dz_web_sum(double a, double b);
