// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:native_toolchain_zig`.
@ffi.DefaultAsset('package:minimal_example/minimal_example.dart')
library;

import 'dart:ffi' as ffi;

/// A direct FFI function with no session or wire format.
@ffi.Native<ffi.Int64 Function(ffi.Int64, ffi.Int64)>(symbol: 'add')
external int add(int a, int b);
